# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: testing
    
    steps:
    - name: Set env variable
      run: echo "NEPTUNE_API_TOKEN=${{ secrets.TEST_TOKEN }}" >> $GITHUB_ENV
    - name: Test
      run: echo $NEPTUNE_API_TOKEN
